# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UserLoginViewer
                                 A QGIS plugin
 A plugin to log in and show user-specific data from a PostgreSQL database
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-21
        copyright            : (C) 2025 by EDR CONTINUOUS INFORMATION PVT. LTD.
        email                : edr@edrinfo.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load UserLoginViewer class from file UserLoginViewer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .user_login_viewer import UserLoginViewer
    return UserLoginViewer(iface)
