"""
constants.py

Defines which fields are editable for each user role in the application.
"""

EDITABLE_FIELDS = {
    # RFDB Production Leaders
    'rfdb_production_leaders': [
        'rfdb_allotted_date',
        'rfdb_completed_date',
        'rfdb_production_done_by',
        'rfdb_production_emp_id',
        'rfdb_production_remarks',
        'rfdb_production_status',
        'rfdb_production_time_taken',
    ],

    # SILOC Production Leaders
    'siloc_production_leaders': [
        'siloc_production_allotted_date',
        'siloc_production_autodetection_status',
        'siloc_production_completed_date',
        'siloc_production_done_by',
        'siloc_production_emp_id',
        'siloc_production_remarks',
        'siloc_production_sign_count',
        'siloc_production_status',
        'siloc_production_time_taken',
    ],

    # SILOC QC Leaders
    'siloc_qc_leaders': [
        'siloc_qc_allotted_date',
        'siloc_qc_completed_date',
        'siloc_qc_done_by',
        'siloc_qc_emp_id',
        'siloc_qc_remarks',
        'siloc_qc_sign_count',
        'siloc_qc_status',
        'siloc_qc_time_taken',
    ],

    # RFDB QC Leaders
    'rfdb_qc_leaders': [
        'delivery_status',
        'delivered_date',
        'rfdb_attri_qc_allotted_date',
        'rfdb_attri_qc_completed_date',
        'rfdb_attri_qc_done_by',
        'rfdb_attri_qc_emp_id',
        'rfdb_attri_qc_remarks',
        'rfdb_attri_qc_status',
        'rfdb_attri_qc_time_taken',
        'rfdb_path_association_production_allotted_date',
        'rfdb_path_association_production_completed_date',
        'rfdb_path_association_production_done_by',
        'rfdb_path_association_production_emp_id',
        'rfdb_path_association_production_remarks',
        'rfdb_path_association_production_status',
        'rfdb_path_association_production_time_taken',
        'rfdb_path_association_qc_allotted_date',
        'rfdb_path_association_qc_completed_date',
        'rfdb_path_association_qc_done_by',
        'rfdb_path_association_qc_emp_id',
        'rfdb_path_association_qc_remarks',
        'rfdb_path_association_qc_status',
        'rfdb_path_association_qc_time_taken',
        'rfdb_qc_allotted_date',
        'rfdb_qc_completed_date',
        'rfdb_qc_done_by',
        'rfdb_qc_emp_id',
        'rfdb_qc_remarks',
        'rfdb_qc_status',
        'rfdb_qc_time_taken',
        'rfdb_qa_allotted_date',
        'rfdb_qa_completed_date',
        'rfdb_qa_done_by',
        'rfdb_qa_emp_id',
        'rfdb_qa_remarks',
        'rfdb_qa_status',
        'rfdb_qa_time_taken',
        'rfdb_roadtype_qc_allotted_date',
        'rfdb_roadtype_qc_completed_date',
        'rfdb_roadtype_qc_done_by',
        'rfdb_roadtype_qc_emp_id',
        'rfdb_roadtype_qc_remarks',
        'rfdb_roadtype_qc_status',
        'rfdb_roadtype_qc_time_taken',
    ],
    # RFDB grand Leaders
    'grand_leaders':[
       'rfdb_production_emp_id',
       'rfdb_production_done_by',
       'rfdb_allotted_date',
       'rfdb_completed_date',
       'rfdb_production_time_taken',
       'rfdb_production_status',
       'rfdb_production_remarks',
       'siloc_production_emp_id',
       'siloc_production_done_by',
       'siloc_production_allotted_date',
       'siloc_production_completed_date',
       'siloc_production_time_taken',
       'siloc_production_sign_count',
       'siloc_production_autodetection_status',
       'siloc_production_status','siloc_production_remarks',
       'siloc_qc_emp_id','siloc_qc_done_by','siloc_qc_allotted_date',
       'siloc_qc_completed_date',
       'siloc_qc_time_taken',
       'siloc_qc_sign_count',
       'siloc_qc_status','siloc_qc_remarks',
       'rfdb_path_association_production_emp_id',
       'rfdb_path_association_production_done_by',
       'rfdb_path_association_production_allotted_date',
       'rfdb_path_association_production_completed_date',
       'rfdb_path_association_production_time_taken',
       'rfdb_path_association_production_status',
       'rfdb_path_association_production_remarks',
       'rfdb_qc_emp_id',
       'rfdb_qc_done_by',
       'rfdb_qc_allotted_date',
       'rfdb_qc_completed_date',
       'rfdb_qc_time_taken',
       'rfdb_qc_status',
       'rfdb_qc_remarks',
       'rfdb_attri_qc_emp_id',
       'rfdb_attri_qc_done_by',
       'rfdb_attri_qc_allotted_date',
       'rfdb_attri_qc_completed_date',
       'rfdb_attri_qc_time_taken',
       'rfdb_attri_qc_status',
       'rfdb_attri_qc_remarks',
       'rfdb_roadtype_qc_emp_id',
       'rfdb_roadtype_qc_done_by',
       'rfdb_roadtype_qc_allotted_date',
       'rfdb_roadtype_qc_completed_date',
       'rfdb_roadtype_qc_time_taken',
       'rfdb_roadtype_qc_status',
       'rfdb_roadtype_qc_remarks',
       'rfdb_qa_emp_id',
       'rfdb_qa_done_by',
       'rfdb_qa_allotted_date',
       'rfdb_qa_completed_date',
       'rfdb_qa_time_taken',
       'rfdb_qa_status',
       'rfdb_qa_remarks',
       'rfdb_path_association_qc_emp_id',
       'rfdb_path_association_qc_done_by',
       'rfdb_path_association_qc_allotted_date',
       'rfdb_path_association_qc_completed_date',
       'rfdb_path_association_qc_time_taken',
       'rfdb_path_association_qc_status',
       'rfdb_path_association_qc_remarks',
       'delivery_status',
       'delivered_date'
    ]
}
